### ISSUE TITLE
Summary code has an incorrect function

### ISSUE THREAD

**Issue by mevanstron** [learn-co-curriculum/redux-dispatch#10]
lines 12 - 19 of the Summary code read: 

function dispatch(action){
    state = changeState(state, action)
}
 
function dispatch(action){
    state = changeState(state, action)
    render()
}
I believe they should read:

function render(){
    document.setInnerHTML = state.counter
}
 
function dispatch(action){
    state = changeState(state, action)
    render()
}

**Comment by maxwellbenton** [comment]
Thank you for spotting this issue and providing feedback, @mevanstron.

We have updated the materials and believe your issue to have been resolved.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
