### ISSUE TITLE
Counter typo?

### ISSUE THREAD

**Issue by alyssa0528** [learn-co-curriculum/redux-dispatch#11]
In the last two code examples in this lesson, should it be "state.count" instead of "state.counter" in the render functions? It's noted as "state.count" in all previous code examples.

**Comment by maxwellbenton** [comment]
Hi @alyssa0528,

Thanks for spotting this and providing feedback. We've updated this lesson and fixed the code snippet typos so that all examples show `state.count`.

Thank you for contributing!
