### ISSUE TITLE
setInnerHTML??

### ISSUE THREAD

**Issue by AkaKuro4Ever** [learn-co-curriculum/redux-dispatch#12]
Hi, I've been checking everywhere online, but I can't find a reference of #setInnerHTML, and I can't seem to make it work in the console. Is it correct, or am I incorrect?

**Comment by maxwellbenton** [comment]
Hi @AkaKuro4Ever,

Thank you for spotting this error and providing feedback. We've corrected the code snippets in this lesson so that they use a valid (and more updated) approach for setting HTML with `textContent`.

Thank you for contributing!
