### ISSUE TITLE
Typos in the final 2 code snippets?

### ISSUE THREAD

**Issue by annaconaway19** [learn-co-curriculum/redux-dispatch#13]
I think `document.setInnerHTML = state.counter` should read `document.setInnerHTML = state.count`. There is no reference to counter anywhere in this example.

**Comment by maxwellbenton** [comment]
Hi @annaconaway19,

Thank you for spotting this and providing feedback. These typos have been fixed so all examples read `state.count`.

Thanks for contributing!
