### ISSUE TITLE
innerHTML is bad practice

### ISSUE THREAD

**Issue by RylanBauermeister** [learn-co-curriculum/redux-dispatch#15]
References to it should be removed and replaced with `.textcontent`, if only to avoid exposure to poor methodologies.

**Comment by jyang81** [comment]
Agreed.

**Comment by maxwellbenton** [comment]
Hi @RylanBauermeister,

Thank you for pointing this out. We agree and have updated this lesson's instructions to use `textContent` instead.

Thank you for contributing!
