### ISSUE TITLE
Error opening lesson

### ISSUE THREAD

**Issue by cbituin** [learn-co-curriculum/redux-dispatch#16]
Lesson does not open in Learn IDE with `learn open redux-dispatch-v-000`

Lesson opens with `learn open redux-dispatch`

**Comment by maxwellbenton** [comment]
Hi @cbituin,

Thank you for providing this feedback. It looks like the `v-000` version fell out of sync with our canonical repository of the lesson. I've updated the `v-000` lesson and confirmed that `learn open redux-dispatch-v-000` will now work going forward.

Thank you for contributing!
