### ISSUE TITLE
when running `dispatch` function, the incremented state value is not displayed

### ISSUE THREAD

**Issue by jrodden1** [learn-co-curriculum/redux-dispatch#17]
I thought I had done something incorrectly after I tried the steps in the code block pictured at the bottom.  

With `dispatch` being declared as a function with no return value, I got `undefined` after manually running the function.  The function did update the state as expected, I just thought it didn't / I did something wrong because of what the code block said I should expect after running that command `// => 1` but I got `undefined`.   

![Redux Dispatch Example 2019-10-28 11-35-38](https://user-images.githubusercontent.com/39208179/67702343-2e9d5c80-f977-11e9-8900-3a47e3d51f0d.png)

**Code Block**
![Learn - Nested Routes Code Along 2019-10-28 11-28-59](https://user-images.githubusercontent.com/39208179/67701925-753e8700-f976-11e9-882b-add99bd64d25.png)

**Comment by jrodden1** [comment]
By the end of the lesson this issue doesn't matter, but I suppose I was just trying to point out some potential confusion that may come up.  🤷‍♂️😊

**Comment by maxwellbenton** [comment]
Hi @jrodden1,

Thanks for catching this! I've updated the two code snippets where this would occur so `dispatch` returns state, which should resolve this issue.

Thank you again!
