### ISSUE TITLE
Unclear description of flow of control

### ISSUE THREAD

**Issue by jcpny1** [learn-co-curriculum/redux-dispatch#7]
The text in the readme doesn't seem to match the example. (line 81)
_When we call dispatch, this calls our changeState reducer, and passes the changeState reducer the action object. The changeState reducer references the already declared state and passes that through. And the changeState reducer has access to the state object because the state object is declared in global scope._
It seems that changeState() has access to state because it's in the argument list, not because it's a global variable.

**Comment by maxwellbenton** [comment]
Thank you for spotting this issue and providing feedback. You are right, changeState() has access to the state via the argument list.

We have updated the materials and believe your issue to have been resolved.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
